# docker-compose.yml
services:
  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"   
    restart: unless-stopped

  api:
    build: ./api
    env_file:
      - ./api/.env
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "3000:3000"   # host nginx proxies to this
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    ports: [ "80:80" ]       # public entrypoint
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/static:/usr/share/nginx/html:ro
    depends_on: [ api ]
    restart: unless-stopped
  
volumes:
  redis_data:
